repos:
  - repo: local
    hooks:
      - id: mix-format
        name: mix format
        entry: mix format
        language: system
        files: \.exs?$
        pass_filenames: false

      - id: mix-credo
        name: mix credo
        entry: mix credo --strict
        language: system
        files: \.exs?$
        pass_filenames: false

      - id: mix-compile
        name: mix compile
        entry: mix compile --warnings-as-errors
        language: system
        files: \.exs?$
        pass_filenames: false
